[package]
name = "git-broom"
version = "0.2.0"
edition = "2021"
description = "Helper tool to clean up local merged Git branches.\nDefine protected branches (comma-separated) with git configuration under the key `broom.protectedbranches`.\nEx: git config --local broom.protectedbranches main,develop"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
gix-config = "0.23.0"
